### ISSUE TITLE
API design minor improvements: POST and GET

### ISSUE THREAD

**Issue by ricgby** [grupokindynos/plutus#1]
**Is your feature request related to a problem? Please describe.**
The following endpoints are called by the GET function:
- api.GET("/validate/address/:coin/:address", walletsCtrl.ValidateAddress)
- api.GET("/send/address/:coin/:address", walletsCtrl.SendToAddress)
- api.GET("/send/cold/:coin", walletsCtrl.SendToColdStorage)
- api.GET("/send/exchange/:coin", walletsCtrl.SendToExchange)

**Describe the solution you'd like**
Perhaps they should be POST instead.

**Additional context**
This is just a design opinion, and should not be considered if this affects the functionality of the API.

**Comment by ricgby** [comment]
@eabz What do you think, should we change them to POST?

**Comment by eabz** [comment]
Agree, they should also include a second layer protection. I'll change it to be post and use JWE.

**Comment by eabz** [comment]
Fixed on #3 

Needs documentation update
