### ISSUE TITLE
API design minor improvements: same structure for all data returns

### ISSUE THREAD

**Issue by ricgby** [grupokindynos/plutus#2]
**Is your feature request related to a problem? Please describe.**
When you call {{PLUTUS_URL}}/address/:coin it returns this:

{
    "data": "PVHkFpQWoTdGbvZbXSqNcd4i6FWXSfPLiB",
    "status": 1
}

I think it would be better if it returned this:

{
    "data": {"address": "PVHkFpQWoTdGbvZbXSqNcd4i6FWXSfPLiB" }
    "status": 1
}

**Additional context**
This would make all the call return the same structure, and we won´t need to have more than 1 model for the services that will consume this API.

Should we change this? @eabz

**Comment by eabz** [comment]
Yep. Let me work it.
