### ISSUE TITLE
[Wallets] Update ZCoin Wallets && Blockbook

### ISSUE THREAD

**Issue by ricgby** [grupokindynos/plutus#6]
**Is your feature request related to a problem? Please describe.**
ZCOIN wallet needs to be updated to latest version.

**Describe the solution you'd like**
Upload to this version: https://github.com/zcoinofficial/zcoin/releases/tag/v0.13.8.8

**Additional context**
This is a mandatory update.

**Comment by eabz** [comment]
Partially replaced by #9

**Comment by eabz** [comment]
Updated resyncing
